### ISSUE TITLE
How you make difference between multiple same class type objects?

### ISSUE THREAD

**Issue by Hesamedin** [Zookey/UniversalPreferences#1]
Hi, Thanks for the lib. This is interesting.
I saw you sample but I couldn't figure out how you return correct result if there are more than a same class type object or how you store them in a way that not override each other. For example how you store 3 String items?

UniversalPreferences.getInstance().put("string", "value_1");
UniversalPreferences.getInstance().put("string", "value_2");
UniversalPreferences.getInstance().put("string", "value_3");

What is output of `String stringValue = UniversalPreference.getInstance().get("string", "");`?

**Comment by Zookey** [comment]
Hi, 

I think I should write better docs, since "string" is just the key not object type.

`UniversalPreferences.getInstance().put("string", "value_1");
`
This is saving String object with key "string" and value "value_1".

`UniversalPreferences.getInstance().put("country", "Canada");
`
This is saving String object with key "country" and value "Canada".

So, you can put whatever you want as first value for put method, but the second value determinate object type.

Does this solve your question?

**Comment by Hesamedin** [comment]
ah, shiiit, the name totally confused me :)
Thanks for prompt reply
